### ISSUE TITLE
Inconsistency when batching

### ISSUE THREAD

**Issue by p4skal** [IntellectualSites/PlotSquared-Legacy#25]
### Server type:
- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [X] Sponge
- [x] NukkitX

### Minecraft Version:
Every Version, even the V5.

### Description of the problem:
In the SQLManager are 3 maps with Database-statements (Tasks) in it. These tasks are grouped by plot / player / cluster in queues. Every time the sendBatch method is fired, one task of each queue gets executed. 
Sometimes tasks do not persist in the database, meaning these tasks don't get executed. So the application cache got the correct information, but the database not. After a restart of the server, some actions aren't there anymore. 

### How to replicate:
So to replicate it, one map must have 3 or more tasks in one queue. And a map that is processed behind it must not be empty and need's to have a maximum of one task per queue.
Example:
plotTasks: {Plot#1=Queue[Task#1,Task#2,Task#3]}
playerTasks: {c53...=Queue[Task#4]}

In the first batch, Task#1 and Task#4 are executed. So the maps look like this:
plotTasks: {Plot#1=Queue[Task#2,Task#3]}
playerTasks: {c53...=Queue[]}
Note that playerTasks queue is empty, but the map entry is not removed.

In the second batch, Task#2 is executed. The count variable after the first block is 1. When entering the playerTasks block the count is set to 0. Because the queue is empty, it continues before the count can be incremented. Resulting in the count being 0 and the plotTasks map being cleared.

There is no third batch because Task#3 got cleared.

See the next section for a real-world example.
### Relevant console output, log lines, and/or screenshots:
I have added some debugs in the method head and before clearing. I set the delay for the next batch to 20 seconds.
```
p4skal issued server command: /p remove Lazzule       // trigger PlotTask for 8;-9
p4skal issued server command: /p remove Valaphee      // trigger PlotTask for 8;-9
p4skal issued server command: /p remove AbgegrieftHD  // trigger PlotTask for 8;-9
p4skal issued server command: /p toggle chat          // trigger PlayerTask for c537070e-775e-43a8-8d12-36f94ac03e2f


Before first Executing Batch:
List PlotTasks: 1:
 - plotworld;8;-9 - 3, [com.intellectualcrafters.plot.database.SQLManager9@1d654cfa, com.intellectualcrafters.plot.database.SQLManager9@3e611351, com.intellectualcrafters.plot.database.SQLManager9@60b0dcdb]
List PlayerTasks: 1:
 - c537070e-775e-43a8-8d12-36f94ac03e2f - 1, [com.intellectualcrafters.plot.database.SQLManager$50@56ef8bba]
List ClusterTasks: 0:
// -> 3 PlotTasks for 8;-9 | 1 Executed, 2 Remaining
// -> 1 PlayerTask for c53... | 1 Executed, 0 Remaining


Before second Executing Batch:
List PlotTasks: 1:
 - plotworld;8;-9 - 2, [com.intellectualcrafters.plot.database.SQLManager9@3e611351, com.intellectualcrafters.plot.database.SQLManager9@60b0dcdb]
List PlayerTasks: 1:
 - c537070e-775e-43a8-8d12-36f94ac03e2f - 0, []
List ClusterTasks: 0:
// -> 2 PlotTasks for 8;-9 | 1 Executed, 1 Remaining
// -> 0 PlayerTasks for c53... | 0 Executed, deleted

Clearing PlotTasks: 1:
 - plotworld;8;-9 - 1, [com.intellectualcrafters.plot.database.SQLManager9@60b0dcdb]
// -> the remaining 1 PlotTask is cleared and not executed.


// /plot info before restart shows none of the 3 accounts.
// /plot info after restart shows Abgegrieft as trusted
```

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared-Legacy/issues?q=is%3Aissue+is%3Aopen+)
- [X] I made sure I am using the latest release version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [X] I didn't read but checked everything above.

**Comment by N0tMyFaultOG** [comment]
Fixed in https://github.com/IntellectualSites/PlotSquared-Legacy/commit/4514d39bbd814c7f18521f6502dc7eabbfe78435
