### ISSUE TITLE
plot visit doenst work on merged plots

### ISSUE THREAD

**Issue by Dweezy750** [IntellectualSites/PlotSquared-Legacy#50]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
- [X] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*

### Minecraft Version:
- [X] Minecraft 1.16.4, paper-342

### Server build info: 
This server is running Paper version git-Paper-342 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)

### Description of the problem:
/plot visit <alias-name> doesnt correctly work on merged-plots.

### How to replicate:
claim and merge some plots, set an alias, go away and try /plot visit alias-name. can be done with or without reboot.

## Additional Information:
There's a no error at all, no ingame error, no console error, nothing, just a blank command input with no response when typing /plot visit alias-name

I'm using MySQL and it looks like "all" the merged plots are getting the same "alias" set. So it looks like if there's multiple, same alias-names in the MySQL that plotsquared cant decided which plot to take. The alias is been set in the MySQL but not display in the /plot info. Typing again /plot alias set somename -> Results in: The alias is already been taken.

I would also be cool if "plot visit alias-name" teleports the player to the "plot sethome"-coordinates

![2020-12-24_12 36 42](https://user-images.githubusercontent.com/76556748/103086720-984de080-45e5-11eb-9e43-534f63613673.png)
![z](https://user-images.githubusercontent.com/76556748/103087183-f29b7100-45e6-11eb-8cb7-db382be7b604.png)

### Other plugins being used on the server:
Plugins (41): AAC5, AdvancedAchievements, AdvancedEnchantments, AdvancedPortals, AuctionHouse, BeastWithdraw, BuycraftX, Citizens, CitizensCMD, Clans-Spigot-Part, CrateReloaded, Essentials, Essentials_WarpGUI, FastAsyncWorldEdit (WorldEdit), FriendsAPIForPartyAndFriends, GadgetsMenu, HolographicDisplays, Hyperverse, Jobs, LPC, LuckPerms, mcMMO, PartyAndFriendsGUI, PerWorldInventory, PlaceholderAPI, PlotSquared, PremiumVanish, ProtocolLib, Quests, QuickShop, RoseStacker, ShopGUIPlus, TAB, TradeSystem, UltimateTimber, Vault, ViaBackwards, ViaVersion, VotingPlugin, WorldEditSelectionVisualizer, WorldGuard

### Relevant console output, log lines, and/or screenshots:

# AFFIRMATION OF COMPLETION:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared-Legacy/issues?q=is%3Aissue+is%3Aopen+)
- [X] I made sure I am using the latest release version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by N0tMyFaultOG** [comment]
This is the repo for legacy issues, if you use v5, create an issue here: https://issues.intellectualsites.com/
