### ISSUE TITLE
Loose Trident on Plot

### ISSUE THREAD

**Issue by supermem99** [IntellectualSites/PlotSquared-Legacy#68]
# Bug Report Template:

## Required Information section:
> ALL FIELDS  IN THIS SECTION ARE REQUIRED, and must contain appropriate information
### Server type:
**Select one**

- [x] Spigot / Paper *(CraftBukkit should not be used, re-test with Spigot first!)*
- [] Sponge
- [] NukkitX

### Minecraft Version:
**Select one**

- [x] Minecraft 1.16.5
- [] Minecraft 1.12.2
- [] Minecraft 1.11.2
- [] Minecraft 1.10.2
- [] Minecraft 1.9.4
- [] Minecraft 1.8.8
- [] Minecraft Bedrock Edition *specify version*:
- [] Sponge *specify version*:

### Server build info: 

```This server is running Paper version git-Paper-643 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 62 version(s) behind
Previous version: git-Paper-629 (MC: 1.16.5)
Paste the output here, between the tick marks, replacing this text
```

### Description of the problem:

My Users lost their trident, if they throw it away from their plots on survival.

### How to replicate:

1. Go on your Plots on Survival Mode
2. Enchant your Trident with loyality
3. throw it away from your plot.
4. Then you Lose your trident and don't get it back

## Additional Information:
> The information here is optional for you to provide, however it may help us to more readily diagnose any compatibility and bug issues.

### Other plugins being used on the server:

Its 
### Additional relevant comments/remarks:

# AFFIRMATION OF COMPLETION:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared-Legacy/issues?q=is%3Aissue+is%3Aopen+)
- [x] I made sure I am using the latest release version of PlotSquared
- [X] I made sure the bug/error is not caused by any other plugin
- [] I didn't read but checked everything above.

**Comment by NotMyFault** [comment]
That is only for legacy. Maintain your server and raise an issue here: https://github.com/IntellectualSites/PlotSquared
